# This is a basic workflow to help you get started with Actions

name: Build

on:
  workflow_dispatch

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r23c
          add-to-path: /opt/hostedtoolcache/ndk/r23c
        env:
          ANDROID_NDK_HOME: /opt/hostedtoolcache/ndk/r23c
      # Runs a single command using the runners shell
      - name: Setup Python
        uses: actions/setup-python@v4.0.0
        with:
          python-version: 3.9.0
         
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18
      
      - name: Build liblzma
        run: bash ./build.sh build_liblzma
      
      - name: Build openssl
        run: bash ./build.sh build_openssl
        
      - name: Build libcurl
        run: bash ./build.sh build_libcurl
        
      - name: Build libkrb5
        run: bash ./build.sh build_libkrb5
      
      - name: Build mongo-tools
        run: bash ./build.sh build_mongo_tools
      
      - name: Build mongod
        run: bash ./build.sh build_mongod
        
      - name: Strip mongod
        run: bash ./build.sh strip_mongod
        
      - name: Upload build
        uses: actions/upload-artifact@v3
        with:
          name: Mongodb
          path: |
            install/usr/bin/mongod
            install/usr/bin/mongos
            install/usr/bin/mongo
            install/usr/bin/bsondump
            install/usr/bin/mongodump
            install/usr/bin/mongoexport
            install/usr/bin/mongofiles
            install/usr/bin/mongoimport
            install/usr/bin/mongorestore
            install/usr/bin/mongostat
            install/usr/bin/mongotop
            
            

  


